### PR TITLE
bigger header & text wrap

### PR DESCRIPTION
**Pull request by Stefan-Radu**
* make text wrap for long lines on mobile
* have the header be overall bigger

### CODE REVIEW

**Comment by Mathis-Dory** [comment]
@Stefan-Radu  You asked for my review but the PR is still in Draft, I assume I do not have to review it until it is not ready ?

**Comment by Stefan-Radu** [comment]
@Mathis-Dory sure. I'm not really sure how to approach this going further. suggestions are welcome

**Comment by Mathis-Dory** [comment]
> @Mathis-Dory sure. I'm not really sure how to approach this going further. suggestions are welcome

Why not, can be a good way to have a more "personalized" website maybe I am gonna add some styles after the exam / during holidays :)

**Comment by Stefan-Radu** [comment]
@Mathis-Dory I'll merge and close this, as honestly what I wanted to do with it at that point is already done. We can open another issue / PRs for style changes

**Pull request merged**
