### PR TITLE
4 bug tags redirection to not found

### PR DESCRIPTION
**Pull request by Mathis-Dory**
### Changed

- Merged https://github.com/dothidden/writeups/pull/17/commits/278ce0f037bcdd4a75018c4c80f654aa423ecaa9

### CODE REVIEW

**Comment by Mathis-Dory** [comment]
@Stefan-Radu I merged your branch here so we have the link with the issue because that was the branch created for the issue. I still found a problem everything work except for the sockpuppet tag:

image
image

**Comment by Stefan-Radu** [comment]
oh wow okay, I will take a look

**Comment by Mathis-Dory** [comment]
> oh wow okay, I will take a look
> 
> edit: I took a look. It happens because there is no `sockpuppet` tag in the ctf _index.md file. I'd still say it's a bug, since we will surely forget to properly label ctfs.

So what can we do the resolve it ? :)

**Comment by Mathis-Dory** [comment]
> > oh wow okay, I will take a look
> > edit: I took a look. It happens because there is no `sockpuppet` tag in the ctf _index.md file. I'd still say it's a bug, since we will surely forget to properly label ctfs.
> 
> So what can we do the resolve it ? :)

@Stefan-Radu ?

**Comment by Stefan-Radu** [comment]
> > > oh wow okay, I will take a look
> > > edit: I took a look. It happens because there is no `sockpuppet` tag in the ctf _index.md file. I'd still say it's a bug, since we will surely forget to properly label ctfs.
> > 
> > 
> > So what can we do the resolve it ? :)
> 
> @Stefan-Radu ?

So, what I was thinking is that we can implement it in such a way that it only relies on the tags from the pages. I have a pretty solid idea of how to do that, but will probably get to it in the next few days (starting on Tuesday most likely)

> 
> Also we have to rebase it before merging I see there are conflicts now

Will rebase no problem.

**Comment by Mathis-Dory** [comment]
> 

Ok sounds a good idea too me thx :)

**Review by Stefan-Radu — COMMENTED** [review]
@Mathis-Dory you can test again. I think this it should be solved

**Comment by Mathis-Dory** [comment]
@Stefan-Radu  are you sure it's resolve ? Because I am not able to run It locally 
image

**Comment by Stefan-Radu** [comment]
> @Stefan-Radu are you sure it's resolve ? Because I am not able to run It locally image

image

for me it works. we can make a short call on discord if you have time to see why it doesn't work

**Pull request merged**
