### PR TITLE
28 refactor ctf writeups for a ctf should be sorted alphabetically

### PR DESCRIPTION
**Pull request by Mathis-Dory**
### Added

- Display a nice message is a CTF section is empty (ex: UMDCTF)

### Changed

- Sort writeup by name
- Add capital letters in the title of Zzz, Bf, Geoguesser write-ups

### CODE REVIEW

**Comment by Stefan-Radu** [comment]
@Mathis-Dory I had only one comment regarding the text. I also added two small commits to this as they kinda fit. Check them out and after that I think we're good to go.

LMK what you think about the text suggestion

**Comment by Mathis-Dory** [comment]
> @Mathis-Dory I had only one comment regarding the text. I also added two small commits to this as they kinda fit. Check them out and after that I think we're good to go.
> 
> LMK what you think about the text suggestion

Perfect for me, I'am the PR author so I can not approve the changes, you can do it and merge it :)

**Comment by Mathis-Dory** [comment]
btw what do you mean by the text suggestion ? If it's #43 I already replied :)

**Comment by Costinteo** [comment]
Why did you change writeup names? Originally they were all lowercase, shouldn't we keep the original name?

**Comment by Stefan-Radu** [comment]
> btw what do you mean by the text suggestion ? If it's #43 I already replied :)

see suggestions please

**Comment by Stefan-Radu** [comment]
> Why did you change writeup names? Originally they were all lowercase, shouldn't we keep the original name?
> 
> Also, I think writeups for each CTF would be better sorted by their main category (pwn, rev, etc..).

I agree that the challenge names should stay the same. Regarding the sort by category idk what to say. I can see how it could work, but also, having the alphabetically sorted is also pretty easy to navigate imo. (also that custom by_tag sort would be a bit more work to do lol)

**Review by Stefan-Radu — CHANGES_REQUESTED** [review]

**Comment by Mathis-Dory** [comment]
> Why did you change writeup names? Originally they were all lowercase, shouldn't we keep the original name?
> 
> Also, I think writeups for each CTF would be better sorted by their main category (pwn, rev, etc..).

I did it because I was afraid it mess with the alphabetical sort and alsoI think it looks better to have everything with a capital letter at the beginning but we can change it.

**Comment by Mathis-Dory** [comment]
@Stefan-Radu you have to review the changes because you did a suggestion so the PR is blocked until you accept my new version :)

**Pull request merged**
