### PR TITLE
24 refactor add n00bz writeup

### PR DESCRIPTION
**Pull request by Stefan-Radu**

### CODE REVIEW

**Comment by Stefan-Radu** [comment]
@Costinteo I'll let this open in case you want to add anything else

**Comment by Stefan-Radu** [comment]
@Costinteo are you gonna add anything more to this?

**Comment by Costinteo** [comment]
Yes, please don't close it. I will close it myself.

**Comment by Costinteo** [comment]
Or actually, you can close the PR and I can make my own later.

**Pull request merged**
