### PR TITLE
add defcamp 2023 boze writeup

### PR DESCRIPTION
**Pull request by SecioreanuStefanita**

### CODE REVIEW

**Comment by Costinteo** [comment]
Use the commit message structure we agreed on.

**Review by Costinteo — CHANGES_REQUESTED** [review]
Use proper commit message structure

**Comment by Mathis-Dory** [comment]
> Use proper commit message structure

I more than approve your comment

**Comment by Mathis-Dory** [comment]
@SecioreanuStefanita  UPPP

**Comment by Mathis-Dory** [comment]
@Costinteo what should we do lol

**Review by Costinteo — APPROVED** [review]
god damn it can we merge this it's already been 6 months....

**Pull request merged**
